language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - NODE_JS_VERSION=5

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - phpenv config-add tests/travis.ini
  - nvm install node

install:
  - bash build/install.sh
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer install --no-interaction

script:
  - bash build/build.sh
  - phpunit --verbose --stderr --coverage-clover build/logs/clover.xml

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - travis_retry php coveralls.phar -v --exclude-no-stmt

notifications:
  webhooks:
    - http://build.miaoxingyun.com/travis-notifications
